import os
import sys


def generate_entity_file(src, dst, type_name, pack_name="game_types"):
    found_files = []

    # verify source directory exists
    if not os.path.exists(src):
        print(f"Error: Source directory '{src}' does not exist.")
        return []

    for _, _, files in os.walk(src):
        for filename in files:
            # get filename without extension
            stem = os.path.splitext(filename)[0]
            found_files.append(stem)

    if not found_files:
        print(f"No files found in: {src}")
        return []

    # for deterministic output
    found_files.sort()

    os.makedirs(os.path.dirname(dst), exist_ok=True)

    try:
        with open(dst, "w", encoding="utf-8") as f:
            f.write("//NOTE: Machine generated by python script\n")
            f.write("\n")
            f.write(f"package {pack_name}\n")
            f.write("\n")
            f.write(f"{type_name}Name :: enum {{\n")
            f.write("\tnil,\n")

            for name in found_files:
                f.write(f"\t{name},\n")

            f.write("}\n")

    except IOError as e:
        print(f"Error on asset generation output: {e}", file=sys.stderr)

    return found_files


if __name__ == "__main__":
    generate_entity_file(
        src="source/game/entities",
        dst="source/systems/entities/type/generated_entity.odin",
        type_name="Entity",
        pack_name="entity_type",
    )
